### ISSUE TITLE
Prefer unit tests over integration tests over end-to-end tests

### ISSUE THREAD

**Issue by olegsych** [Microsoft/ApplicationInsights-aspnetv5#19]
It feels that some recent changes set us on a path of using end-to-end tests over lower-level tests, such as integration and unit tests. I think this is a dangerous trend as it will make changing the code more and more difficult over time, especially by outside contributors, who are not intimately familiar with the test infrastructure. Pull request #17 contains comments describing what actually happened to me while integrating changes in pull request #15 with a relatively small set of the end-to-end `RequestTelemetryTests`.

**Comment by SergKanz** [comment]
I think we discussed this enough. I'd close this for now.

Today:
- we try to test as much as possible using unit tests
- we test basic scenarios on standard template applications using functional tests

We have a two gaps - testing that http channel will be initialized properly for the standard application and testing that application will be working in iisexpress.

I've started wiki page for [testing](https://github.com/Microsoft/ApplicationInsights-aspnetv5/wiki/Testing)
