### ISSUE TITLE
Use Git Flow branching model

### ISSUE THREAD

**Issue by olegsych** [Microsoft/ApplicationInsights-aspnetv5#37]
Open Source projects hosted on GitHub typically use [Git Flow branching model](http://nvie.com/posts/a-successful-git-branching-model). One of its key differences from the "DevDiv branching model" that we fell into is that the Git Flow master branch serves as DevDiv release branch. Git Flow model is simpler for contributors, well documented and well known. I think we should adopt it before going "public".

**Comment by olegsych** [comment]
We discussed this as a team and agreed to use Git Flow. @rinatkar renamed the release branch to release-beta4. @SergKanz and I published v0.30.0.1-beta of the NuGet package and tagged it in the repository. At this point, the (Finishing a release branch)[http://nvie.com/posts/a-successful-git-branching-model/#finishing-a-release-branch] section of Git Flow recommends deleting the branch. Is everyone OK with this?

CC: @abaranch, @upendras, @Sergei-Nikitin

**Comment by SergKanz** [comment]
Do gitflow suggest to mark develop branch as "default" or we need to keep master as "default"?

**Comment by olegsych** [comment]
Git Flow makes no recommendations regarding GitHub configuration. From what I've seen, repos typically have master as the default, because that's what the "customers" will see and they may not even heard of Git Flow. This helps to encourage contribution of bug fixes and small changes by getting them started with the stable, released codebase.

**Comment by SergKanz** [comment]
Great. Let's delete it then

**Comment by upendras** [comment]
+1

**Comment by olegsych** [comment]
release-beta4 branch deleted.
