### ISSUE TITLE
Switch from hard-coded fakes to a dynamic test isolation framework.

### ISSUE THREAD

**Issue by olegsych** [Microsoft/ApplicationInsights-aspnetv5#47]
@SergKanz, @abaranch, @upendras and @Sergei-Nikitin,

Since I will be moving away from the ASP.NET 5 work soon, I think people who will be maintaining this code would be in the best position to choose the test isolation framework we will use. Here is what [Roy Osherove](http://osherove.com/blog), the author of the highly recommended book, [The Art of Unit Testing](http://mslibrary/Books/Pages/Bib/Bib_0353937.aspx) has to say on the subject: [FakeItEasy or NSubstitute, which should I use?](http://osherove.com/blog/2012/6/26/fakeiteasy-or-nsubstitute-which-should-i-use-for-samples-in.html). 

Notice that he recommends *against* using Moq on new projects. He also has a somewhat outdated poll that, shows NSubstitute being the most popular among his blog readers. However, the Microsoft Engineering Excellency team also recommends NSubstitute over Moq on the agile alias when this question comes up.

Here are the links to these frameworks on GitHub.
* [Moq](http://www.github.com/moq/moq4)
* [NSubstitute](http://www.github.com/nsubstitute/nsubstitute)
* [FakeItEasy](http://www.github.com/fakeiteasy/fakeiteasy).

Although all of them are actively maintained, none of them support dnxcore50 at this time. Contributing to Moq and FakeItEasy would be straightforward, while NSubstitute may be a bit harder due to custom tools they use. 

Please comment on your preference.

**Comment by SergKanz** [comment]
My vote is for NSubstitute

**Comment by abaranch** [comment]
We will start supporting dnxcore50 very soon. We need it to be supported by dynamic test isolation framework.

**Comment by olegsych** [comment]
Do you suggest maintaining hand-written fakes until one of these frameworks supports dnxcore?

**Comment by abaranch** [comment]
Yes. We cannot claim that we support a platform if we did not test it.

**Comment by olegsych** [comment]
I don't think anyone is suggesting that we don't test on dnxcore. Whether or not we *run unit tests* on this platform is only a small part in supporting it. While I agree that it would be ideal to do so, we can choose to run the unit tests only on the full framework, while continuing to use functional and manual tests to verify that our code works on dnxcore.

**Comment by SergKanz** [comment]
I propose to close this issue until we have a fakes framework that supports core framework.

**Comment by teddymaef** [comment]
I found this one work with dnxcore50: http://nugot.net/package/LightMock.vNext

**Comment by SergeyKanzhelev** [comment]
Looks interesting. Have you tried it? Does it work for you?
