### ISSUE TITLE
How to remove telemetry and context initializers that were automatically registered?

### ISSUE THREAD

**Issue by abaranch** [Microsoft/ApplicationInsights-aspnetv5#52]

**Comment by olegsych** [comment]
Initializers can be removed in the `ConfigureServices` by from `IServiceCollection`, which is an `IList<ServiceDescriptor>`, by calling its `Remove` method. The `Replace` [extension method](https://github.com/aspnet/DependencyInjection/blob/release/src/Microsoft.Framework.DependencyInjection.Interfaces/ServiceCollectionExtensions.cs) does that and more user-friendly methods could be created if this is a common scenario.

In the `Configure` method, initializers can be removed by obtaining the `TelemetryConfiguration` instance from the `IApplicationBuilder.ApplicationServices` provider and removing required instances from its `TelemetryInitializers` or `ContextInitializers` collections.
